server:
  port: 8081

spring:
  config:
    activate:
      on-profile: local

  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jspdb?serverTimezone=Asia/Seoul
    username: root
    password: 1234

  thymeleaf:
    cache: false

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true